//! Golden-trace tests: verify full pipeline produces identical outputs to Python DSPy 3.1.2.
//!
//! These tests compare our Rust port's message formatting, parsing, and module behavior
//! against golden outputs captured from Python DSPy 3.1.2 with deterministic mock LMs.
//!
//! Golden outputs generated by cross-validation/generate_optimizer_golden.py.

#[cfg(test)]
mod tests {
    use crate::chain_of_thought::ChainOfThought;
    use crate::error::Result;
    use crate::example::Example;
    use crate::lm::{LMConfig, LMResponse, Message, LM};
    use crate::module_trait::Module;
    use crate::predict::Predict;
    use crate::settings;
    use crate::signature::Signature;
    use async_trait::async_trait;
    use std::sync::{Arc, Mutex};

    /// Mock LM that returns predetermined responses and captures messages sent to it.
    struct DeterministicLM {
        responses: Vec<String>,
        call_index: Mutex<usize>,
        history: Mutex<Vec<Vec<Message>>>,
        config: LMConfig,
    }

    impl DeterministicLM {
        fn new(responses: Vec<&str>) -> Self {
            Self {
                responses: responses.iter().map(|s| s.to_string()).collect(),
                call_index: Mutex::new(0),
                history: Mutex::new(Vec::new()),
                config: LMConfig::new("deterministic-mock"),
            }
        }

        fn get_history(&self) -> Vec<Vec<Message>> {
            self.history.lock().unwrap().clone()
        }
    }

    #[async_trait]
    impl LM for DeterministicLM {
        async fn call(
            &self,
            messages: &[Message],
            _config: &LMConfig,
        ) -> Result<Vec<LMResponse>> {
            let mut idx = self.call_index.lock().unwrap();
            if *idx >= self.responses.len() {
                panic!(
                    "DeterministicLM ran out of responses (used {})",
                    *idx
                );
            }
            let response = self.responses[*idx].clone();
            *idx += 1;

            self.history
                .lock()
                .unwrap()
                .push(messages.to_vec());

            Ok(vec![LMResponse {
                text: response,
                usage: None,
            }])
        }

        fn model(&self) -> &str {
            "deterministic-mock"
        }

        fn config(&self) -> &LMConfig {
            &self.config
        }

        fn dump_state(&self) -> serde_json::Value {
            serde_json::json!({"model": "deterministic-mock"})
        }
    }

    // ---- Predict pipeline golden-trace tests ----

    #[tokio::test]
    async fn test_golden_simple_predict_messages() {
        settings::reset_settings();

        let lm = Arc::new(DeterministicLM::new(vec![
            "[[ ## answer ## ]]\n42\n\n[[ ## completed ## ]]",
        ]));

        let sig = Signature::from_string("question -> answer").unwrap();
        let mut predict = Predict::new(sig);
        predict.set_lm(lm.clone());

        let inputs = Example::new().field("question", "What is the meaning of life?");
        let _result = predict.forward(&inputs).await.unwrap();

        // Compare messages sent to LM against Python DSPy 3.1.2 golden output
        let history = lm.get_history();
        assert_eq!(history.len(), 1);
        let sent_messages = &history[0];

        // Expected from Python DSPy 3.1.2
        let expected_system = "Your input fields are:\n\
            1. `question` (str):\n\
            Your output fields are:\n\
            1. `answer` (str):\n\
            All interactions will be structured in the following way, with the appropriate values filled in.\n\
            \n\
            [[ ## question ## ]]\n\
            {question}\n\
            \n\
            [[ ## answer ## ]]\n\
            {answer}\n\
            \n\
            [[ ## completed ## ]]\n\
            In adhering to this structure, your objective is: \n\
            \x20       Given the fields `question`, produce the fields `answer`.";

        let expected_user = "[[ ## question ## ]]\n\
            What is the meaning of life?\n\
            \n\
            Respond with the corresponding output fields, starting with the field `[[ ## answer ## ]]`, and then ending with the marker for `[[ ## completed ## ]]`.";

        assert_eq!(sent_messages.len(), 2);
        assert_eq!(sent_messages[0].role, "system");
        assert_eq!(sent_messages[0].content, expected_system);
        assert_eq!(sent_messages[1].role, "user");
        assert_eq!(sent_messages[1].content, expected_user);
    }

    #[tokio::test]
    async fn test_golden_simple_predict_parsed_output() {
        settings::reset_settings();

        let lm = Arc::new(DeterministicLM::new(vec![
            "[[ ## answer ## ]]\n42\n\n[[ ## completed ## ]]",
        ]));

        let sig = Signature::from_string("question -> answer").unwrap();
        let mut predict = Predict::new(sig);
        predict.set_lm(lm.clone());

        let inputs = Example::new().field("question", "What is the meaning of life?");
        let result = predict.forward(&inputs).await.unwrap();

        assert_eq!(result.get_str("answer"), Some("42"));
    }

    #[tokio::test]
    async fn test_golden_multi_field_predict_messages() {
        settings::reset_settings();

        let lm = Arc::new(DeterministicLM::new(vec![
            "[[ ## reasoning ## ]]\nLet me think about this.\n\n[[ ## answer ## ]]\n42\n\n[[ ## completed ## ]]",
        ]));

        let sig = Signature::from_string("question -> reasoning, answer").unwrap();
        let mut predict = Predict::new(sig);
        predict.set_lm(lm.clone());

        let inputs = Example::new().field("question", "What is 6*7?");
        let _result = predict.forward(&inputs).await.unwrap();

        let history = lm.get_history();
        assert_eq!(history.len(), 1);
        let sent_messages = &history[0];

        // Expected from Python DSPy 3.1.2
        let expected_system = "Your input fields are:\n\
            1. `question` (str):\n\
            Your output fields are:\n\
            1. `reasoning` (str): \n\
            2. `answer` (str):\n\
            All interactions will be structured in the following way, with the appropriate values filled in.\n\
            \n\
            [[ ## question ## ]]\n\
            {question}\n\
            \n\
            [[ ## reasoning ## ]]\n\
            {reasoning}\n\
            \n\
            [[ ## answer ## ]]\n\
            {answer}\n\
            \n\
            [[ ## completed ## ]]\n\
            In adhering to this structure, your objective is: \n\
            \x20       Given the fields `question`, produce the fields `reasoning`, `answer`.";

        let expected_user = "[[ ## question ## ]]\n\
            What is 6*7?\n\
            \n\
            Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]`, and then ending with the marker for `[[ ## completed ## ]]`.";

        assert_eq!(sent_messages.len(), 2);
        assert_eq!(sent_messages[0].role, "system");
        assert_eq!(sent_messages[0].content, expected_system);
        assert_eq!(sent_messages[1].role, "user");
        assert_eq!(sent_messages[1].content, expected_user);
    }

    #[tokio::test]
    async fn test_golden_multi_field_predict_parsed_output() {
        settings::reset_settings();

        let lm = Arc::new(DeterministicLM::new(vec![
            "[[ ## reasoning ## ]]\nLet me think about this.\n\n[[ ## answer ## ]]\n42\n\n[[ ## completed ## ]]",
        ]));

        let sig = Signature::from_string("question -> reasoning, answer").unwrap();
        let mut predict = Predict::new(sig);
        predict.set_lm(lm.clone());

        let inputs = Example::new().field("question", "What is 6*7?");
        let result = predict.forward(&inputs).await.unwrap();

        assert_eq!(result.get_str("reasoning"), Some("Let me think about this."));
        assert_eq!(result.get_str("answer"), Some("42"));
    }

    // ---- ChainOfThought pipeline golden-trace tests ----

    #[tokio::test]
    async fn test_golden_cot_pipeline_messages() {
        settings::reset_settings();

        let lm = Arc::new(DeterministicLM::new(vec![
            "[[ ## reasoning ## ]]\nFirst, I note that 6 * 7 = 42.\n\n[[ ## answer ## ]]\n42\n\n[[ ## completed ## ]]",
        ]));

        let sig = Signature::from_string("question -> answer").unwrap();
        let mut cot = ChainOfThought::new(sig);
        cot.predict_mut().set_lm(lm.clone());

        let inputs = Example::new().field("question", "What is 6*7?");
        let _result = cot.forward(&inputs).await.unwrap();

        let history = lm.get_history();
        assert_eq!(history.len(), 1);
        let sent_messages = &history[0];

        // CoT adds "reasoning" output field. Expected from Python DSPy 3.1.2:
        // Note: instructions preserve original "question -> answer" (NOT "question -> reasoning, answer")
        let expected_system = "Your input fields are:\n\
            1. `question` (str):\n\
            Your output fields are:\n\
            1. `reasoning` (str): \n\
            2. `answer` (str):\n\
            All interactions will be structured in the following way, with the appropriate values filled in.\n\
            \n\
            [[ ## question ## ]]\n\
            {question}\n\
            \n\
            [[ ## reasoning ## ]]\n\
            {reasoning}\n\
            \n\
            [[ ## answer ## ]]\n\
            {answer}\n\
            \n\
            [[ ## completed ## ]]\n\
            In adhering to this structure, your objective is: \n\
            \x20       Given the fields `question`, produce the fields `answer`.";

        let expected_user = "[[ ## question ## ]]\n\
            What is 6*7?\n\
            \n\
            Respond with the corresponding output fields, starting with the field `[[ ## reasoning ## ]]`, then `[[ ## answer ## ]]`, and then ending with the marker for `[[ ## completed ## ]]`.";

        assert_eq!(sent_messages.len(), 2);
        assert_eq!(sent_messages[0].role, "system");
        assert_eq!(
            sent_messages[0].content, expected_system,
            "System message mismatch.\n\nGot:\n{}\n\nExpected:\n{}",
            sent_messages[0].content, expected_system
        );
        assert_eq!(sent_messages[1].role, "user");
        assert_eq!(sent_messages[1].content, expected_user);
    }

    #[tokio::test]
    async fn test_golden_cot_pipeline_parsed_output() {
        settings::reset_settings();

        let lm = Arc::new(DeterministicLM::new(vec![
            "[[ ## reasoning ## ]]\nFirst, I note that 6 * 7 = 42.\n\n[[ ## answer ## ]]\n42\n\n[[ ## completed ## ]]",
        ]));

        let sig = Signature::from_string("question -> answer").unwrap();
        let mut cot = ChainOfThought::new(sig);
        cot.predict_mut().set_lm(lm.clone());

        let inputs = Example::new().field("question", "What is 6*7?");
        let result = cot.forward(&inputs).await.unwrap();

        assert_eq!(
            result.get_str("reasoning"),
            Some("First, I note that 6 * 7 = 42.")
        );
        assert_eq!(result.get_str("answer"), Some("42"));
    }

    // ---- LabeledFewShot golden-trace tests ----
    // Note: RNG sequences differ between Python (Mersenne Twister) and Rust (Mulberry32),
    // so we test patterns (correct count, different per predictor) not exact values.

    #[test]
    fn test_golden_labeled_few_shot_sample_false() {
        // sample=false should take first k in order — deterministic, no RNG
        let sig = Signature::from_string("question -> answer").unwrap();
        let mut predict = Predict::new(sig);

        // Build trainset
        let trainset: Vec<Example> = (0..5)
            .map(|i| {
                Example::new()
                    .field("question", format!("Q{}", i).as_str())
                    .field("answer", format!("A{}", i).as_str())
            })
            .collect();

        // sample=false: just take first k
        let k = 3;
        predict.demos = trainset[..k].to_vec();

        // Should be first k in order, matching Python golden output
        assert_eq!(predict.demos.len(), 3);
        assert_eq!(predict.demos[0].get_str("question"), Some("Q0"));
        assert_eq!(predict.demos[0].get_str("answer"), Some("A0"));
        assert_eq!(predict.demos[1].get_str("question"), Some("Q1"));
        assert_eq!(predict.demos[1].get_str("answer"), Some("A1"));
        assert_eq!(predict.demos[2].get_str("question"), Some("Q2"));
        assert_eq!(predict.demos[2].get_str("answer"), Some("A2"));
    }

    #[test]
    fn test_golden_labeled_few_shot_k_exceeds_trainset() {
        // When k > trainset size, should clamp to trainset size
        let trainset: Vec<Example> = (0..2)
            .map(|i| {
                Example::new()
                    .field("question", format!("Q{}", i).as_str())
                    .field("answer", format!("A{}", i).as_str())
            })
            .collect();

        let k = 5;
        let actual_k = k.min(trainset.len());
        assert_eq!(actual_k, 2); // min(5, 2) = 2
    }
}
